[Rule]
// DIRECT & LAN FIRST
RULE-SET,LAN,DIRECT
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Special.list,DIRECT

// REJECT / ADBLOCK
# RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Purification.list,Purification
# RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/AdBlock.list,AdBlock
# RULE-SET,https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Surge-RULE-SET.list,AdBlock # AWAvenue Ads Rule

// AI / LLM
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/AI.list,AI

// SOCIAL & MESSAGING
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Telegram.list,Telegram
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/X.list,X
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Discord.list,Discord
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Slack.list,Slack
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Facebook.list,Facebook

// MEDIA & ENTERTAINMENT
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/YouTube.list,YouTube
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/TikTok.list,TikTok
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Spotify.list,Spotify
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/ForeignMedia.list,ForeignMedia
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/PornHub.list,PornHub

// BIG TECH & CLOUD SERVICES
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/iCloud.list,iCloud
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Apple.list,Apple
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Google.list,Google
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Microsoft.list,Microsoft
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/GitHub.list,GitHub
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/CloudFlare.list,CloudFlare

// UTILITY & DEVELOPMENT
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/PayPal.list,PayPal
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Crypto.list,Crypto
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/SpeedTest.list,SpeedTest

// GENERAL FALLBACK PROXY
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/main/Surge/Rulesets/Proxy.list,PROXY

// FINAL ROUTING
GEOIP,CN,DIRECT
FINAL,Default