[Rule]
// DIRECT
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/master/Surge/Rulesets/Direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/master/Surge/Rulesets/Apple.list,DIRECT

// REJECT
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/master/Surge/Rulesets/Reject.list,REJECT

// PROXY
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/master/Surge/Rulesets/AI.list,PROXY
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/master/Surge/Rulesets/Media.list,PROXY
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/master/Surge/Rulesets/Social.list,PROXY
RULE-SET,https://raw.githubusercontent.com/funnyzak/network-rules/master/Surge/Rulesets/Proxy.list,PROXY

GEOIP,CN,DIRECT
FINAL,DIRECT